/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.67).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.capgemini.south_node_proxy.application.api;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.validation.Valid;

@Validated
public interface TrafficInfluenceNewZonesApi {

    @Operation(summary = "", description = "", tags={ "Traffic Influence (Incoming)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Zone info notification acknowledged") })
    @RequestMapping(value = "/traffic-influence-new-zones",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> trafficInfluenceNewZonesPost(@Parameter(in = ParameterIn.DEFAULT, description = "Potential new Zones that I2CAT MEO2 returns", required=true, schema=@Schema()) @Valid @RequestBody List<Object> body
);

}

